USE hdata;

DROP TABLE IF EXISTS hdata;

CREATE TABLE DATA_2(
ID int PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
CA2 VARCHAR(100) NOT NULL,
CB2 VARCHAR(100) NOT NULL,
CC2 VARCHAR(100) NOT NULL,
CD2 VARCHAR(100) NOT NULL,
CE2 VARCHAR(100) NOT NULL,
CF2 VARCHAR(100) NOT NULL,
CG2 VARCHAR(100) NOT NULL,
CH2 VARCHAR(100) NOT NULL,
CI2 VARCHAR(100) NOT NULL,
CreateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UpdatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);