USE hdata;

drop table IF EXISTS hdata;

create TABLE DATA_1(
ID int PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
CA VARCHAR(100) NOT NULL,
CB VARCHAR(100) NOT NULL,
CC VARCHAR(100) NOT NULL,
CD VARCHAR(100) NOT NULL,
CE VARCHAR(100) NOT NULL,
CF VARCHAR(100) NOT NULL,
CG VARCHAR(100) NOT NULL,
CH VARCHAR(100) NOT NULL,
CI VARCHAR(100) NOT NULL,
CreateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UpdatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);