DROP TABLE
IF
	EXISTS hdatajobs;
CREATE TABLE hdatajobs (
	jobid INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	jobname VARCHAR ( 100 ) NOT NULL,
	jobpath TEXT NOT NULL,
	jobdesc TEXT NOT NULL,
	jobstatus TINYINT NOT NULL DEFAULT 1,
	createtime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedtime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)